### PR TITLE
Update popup.js

### PR DESCRIPTION
**Pull request by LeftoverCantoneseFood**
I may have done this wrong. But I think you should have an indicator, or something that is displayed when popups are disabled.

also, what's your discord? Sorry if this seems like a weird question. I'm not creepy, I swear.

### CODE REVIEW

**Comment by rohit901** [comment]
That's a good idea, thank you for your PR. 
my discord is rohit901 #0716, don't worry it's not creepy/weird, but I'm not quite active on discord.

**Comment by HolySuicidalTurkey** [comment]
woah. **epic.**

That's my first pull reuqest that's gotten merged! 

:D

**Comment by HolySuicidalTurkey** [comment]
woah. **epic.**
That's my first pull reuqest that's gotten merged! 

#:D

**Comment by LeftoverCantoneseFood** [comment]
woah. **epic.**
That's my first pull reuqest that's gotten merged! 

### :D

**Comment by LeftoverCantoneseFood** [comment]
also, in hindsight, you might want to add a bit more text to the message, like 'use the chrome extension and click "show messages" to re-enable popups'

**Comment by rohit901** [comment]
hey, actually I'm a bit busy these days with college work, so feel free to make the necessary changes, I would gladly merge them in :)

**Comment by LeftoverCantoneseFood** [comment]
okay

**Pull request merged**
